version: 2
jobs:
  deploy-git-pages:
    working_directory: ~/repo
      docker:
          - image: circleci/node:12.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@latest
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: clean
          command: npm run clean
      - run:
          name: deploy
          command: npm run deploy
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@circleci.com"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist public

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-git-pages:
          filters:
            branches:
              only: master
